source "https://rubygems.org"

gem "amp-jekyll", ">= 1.0.3"
gem "autoprefixer-rails"
gem "crass"
gem "font-awesome-sass"
gem "html-proofer"
gem "image_optim_bin" # Optional
gem "image_optim_pack"
gem "image_optim"
gem "jekyll-assets", ">= 3.0.12"
gem "jekyll-feed", ">= 0.15.0"
gem "jekyll-gist"
gem "jekyll-last-modified-at", ">= 1.3.0"
gem "jekyll-paginate-v2", ">= 3.0.0"
gem "jekyll-redirect-from", ">= 0.16.0"
gem "jekyll-seo-tag", ">= 2.6.1"
gem "jekyll-seo"
gem "jekyll-sitemap", ">= 1.4.0"
gem "jekyll", ">= 3.9.0"
gem "jemoji", ">= 0.12.0"
gem "kramdown-parser-gfm", ">= 1.1.0"
gem "mini_magick"
gem "rake"
gem "rouge"
gem "sanitize"
gem "sass"
gem "sprockets", "4.0.0.beta8"
gem "uglifier"