source "https://rubygems.org"

gem "amp-jekyll"
gem "autoprefixer-rails"
gem "crass"
gem "font-awesome-sass"
gem "html-proofer", ">= 3.16.0"
gem "image_optim_bin" # Optional
gem "image_optim_pack"
gem "image_optim"
gem "jekyll-assets"
gem "jekyll-feed"
gem "jekyll-gist"
gem "jekyll-last-modified-at"
gem "jekyll-paginate-v2"
gem "jekyll-redirect-from"
gem "jekyll-seo-tag"
gem "jekyll-seo"
gem "jekyll-sitemap"
gem "jekyll"
gem "jemoji", ">= 0.13.0"
gem "kramdown-parser-gfm"
gem "mini_magick"
gem "rake"
gem "rouge"
gem "sanitize", ">= 5.2.2"
gem "sass"
gem "sprockets", "4.0.0"
gem "uglifier"